kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: insights-proxy-namespace-access
  namespace: insights-proxy
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: insights-on-premise
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccounts:insights-proxy'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
