apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: console-aws-creds
  namespace: openshift-operators
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - '*'
    resourceNames:
      - console-aws-creds